Azure/AzureStack-QuickStart-Templates

bootstorm-vm-boot-time/azuredeploy.json, bootstorm-vm-boot-time/readme.md
Fixed DSC template path to point Azure repository instead of private repository. 
Updated readme file.
=> Changed DSC template path to master git repo

README.md, Sample README.md
Reviewed by CharlesJ and VictorA
=> Guidelines and sample

101-create-storage-account/azuredeploy.parameters.json
Updating parameters file to reflect the actual parameters defined in the template (only one parameter is defined: storageAccountNamePrefix).
=> Updating azuredeploy.parameters.json

rds-deployment/azuredeploy.json
=> fixing location

ad-non-ha/azuredeploy.json, rds-deployment-existing-ad/README.md, rds-deployment-existing-ad/azuredeploy.json, rds-deployment-existing-ad/azuredeploy.parameters.json, rds-deployment-existing-ad/metadata.json
Adding RDS farm template using existing AD.
=> RDS existing AD

rds-deployment-customimage-rdsh/README.md, rds-deployment-customimage-rdsh/azuredeploy.json, rds-deployment-customimage-rdsh/azuredeploy.parameters.json, rds-deployment-customimage-rdsh/metadata.json
RDS using custom os image for RDSH role.
=> RDS using custom os image for RDSH role

101-simple-windows-vm-diag/azuredeploy.json, 101-simple-windows-vm-diag/azuredeploy.parameters.json
- removed storage ednpoint param
- replaced disk endpoints to dynamic
- removed endpoint from param file
=> Dynamic endpoint

101-simple-windows-vm/azuredeploy.json, 101-simple-windows-vm/azuredeploy.parameters.json
Reverts Azure/AzureStack-QuickStart-Templates#89
=> Revert #89 to keep master at AzureStackTechnicalPreview1

101-simple-windows-vm/azuredeploy.json, 101-simple-windows-vm/azuredeploy.parameters.json
Reverts Azure/AzureStack-QuickStart-Templates#87
=> Revert #87 to keep master at AzureStackTechnicalPreview1

docker-swarm-ubuntu/README.md, docker-swarm-ubuntu/azuredeploy-sshkeys.parameters.json, docker-swarm-ubuntu/azuredeploy.json, docker-swarm-ubuntu/deploySwarm.ps1, docker-swarm-ubuntu/parts/configure-swarm-azurestack.sh
=> Docker swarm ubuntu TP2 changes

exchange-2016-non-ha/CSDownloadISO.ps1
CustomScript powershell script to download Exchange ISO.
=> Added Custom Script to download Exchange 2016 CU1

exchange-2016-non-ha/CSDownloadISO.ps1, exchange-2016-non-ha/azuredeploy.json, jetstress-2013-exchange-loadtest/azuredeploy.parameters.json
Exchange storage size parameter updated to in GB
=> Default 4 VMs deployment for Jetstress workload. 

ad-join-domain-ext-win/azuredeploy.json, ad-join-domain-ext-win/azuredeploy.parameters.json
Removed default values from parameters file as the main template has the
correct set of default values
=> AD join domain parameters file fix

101-linux-docker-extension/azuredeploy.parameters.json
Remove VM name and use auto generated value by default
=> Remove VM name

101-linux-customscript-ext/azuredeploy.parameters.json
Remove VM name parameter as default is autogenerated
=> Remove VM name parameter

sharepoint-2013-non-ha/azuredeploy.parameters.json, vs2013-tcta/azuredeploy.parameters.json
Removing unnecessary parameters from the parameters files as the
template already has valid default values
=> Parameters file fixes for SharePoint and Visual Studio templates

rds-deployment-existing-ad/azuredeploy.json
fixing dns lable prefix so, it will work on Azure.
=> fixing dns lable

100-Blank-Template/README.md, 100-Blank-Template/azuredeploy.json, 100-Blank-Template/azuredeploy.parameters.json, 100-Blank-Template/metadata.json
=> Added a blank starter template

sharepoint-2013-non-ha/Readme.md, vs2013-tcta/Readme.md
Updated readme files for the SharePoint 2013 and Visual Studio 2013
templates
=> SharePoint 2013 and VS2013 template readme updates

README.md
=> Update for TP2

rds-deployment-existing-ad/azuredeploy.json
Fixing type string for extensions
=> fixing type string

jetstress-2013-exchange-loadtest/azuredeploy.json, jetstress-2013-exchange-loadtest/azuredeploy.parameters.json, jetstress-2013-exchange-loadtest/readme.md
Fixed links in readme.md
Updated default password complexity
Default IOPS/mailbox are now 10 instead of 1
=> Jetstress: Fixed default IOPS per mailbox

201-Comprehensive/azuredeploy.parameters.json
=> Current file is invalid Json

jetstress-2013-exchange-loadtest/azuredeploy.parameters.json
Reducing jetstress run time and mailbox database size default and switching default test type to ExchangeMailboxProfile
=> Default parameter change

jetstress-2013-exchange-loadtest/azuredeploy.json
Update database size, runtime, and test type defaults.
=> Change parameter defaults

rds-deployment-existing-ad/azuredeploy.json
Add dependencies to public IPs for NICs which use them
=> Add public IP dependencies

exchange-2016-non-ha/azuredeploy.json
=> Point to develop for DSC

201-vmss-custom-script-windows/README.md, 201-vmss-custom-script-windows/azuredeploy.json, 201-vmss-custom-script-windows/azuredeploy.parameters.json, 201-vmss-custom-script-windows/metadata.json, 201-vmss-custom-script-windows/scripts/helloWorld.ps1
Deploy a VM Scale Set of Windows VMs with a custom script extension
=> Deploy a VM Scale Set of Windows VMs with a custom script extension

101-sqladapter-add-hosting-server/README.md, 101-sqladapter-add-hosting-server/azuredeploy.json, 101-sqladapter-add-hosting-server/azuredeploy.parameters.json, 101-sqladapter-add-hosting-server/metadata.json, 101-sqladapter-create-database/README.md, 101-sqladapter-create-database/azuredeploy.json, 101-sqladapter-create-database/azuredeploy.parameters.json, 101-sqladapter-create-database/metadata.json
Adding SQL Adapter 101 templates for adding hosting servers and creating
databases
=> SQL Adapter RP 101 templates

101-mysqladapter-add-hosting-server/README.md, 101-mysqladapter-add-hosting-server/azuredeploy.json, 101-mysqladapter-add-hosting-server/azuredeploy.parameters.json, 101-mysqladapter-add-hosting-server/metadata.json, 101-mysqladapter-create-database/README.md, 101-mysqladapter-create-database/azuredeploy.json, 101-mysqladapter-create-database/azuredeploy.parameters.json, 101-mysqladapter-create-database/metadata.json
Deploys MySQL hosting server and database
=> Template for MySql Hosting Server and Database creation

101-vm-windows-create-api-profile/README.md, 101-vm-windows-create-api-profile/azuredeploy.json, 101-vm-windows-create-api-profile/azuredeploy.parameters.json, 101-vm-windows-create-api-profile/metadata.json
this is a stop gap till we convert all the templates to use api-profile
=> Adding a template with Api Profile, converted the 101-vm-windows-create to use api profile

appservice-fileserver-standalone/README.md, appservice-fileserver-standalone/azuredeploy.json, appservice-fileserver-standalone/azuredeploy.parameters.json, appservice-fileserver-standalone/metadata.json
=> Added domain name label for file server

101-vm-windows-create-passwordfromkv/azuredeploy.json, 101-vmss-windows-vm/azuredeploy.json, 201-vm-windows-pushcertificate/azuredeploy.json, 201-vmss-windows-extension/azuredeploy.json, 201-vmss-windows-vm-largescale/azuredeploy.json
to adapt to Azure terminologies
=> Update 2016-Datacenter-Core to 2016-Datacenter-Server-Core

101-vmss-linux-vm/azuredeploy.json
assuming we do need ssh and not rdp, so changing fwrule from 3899 t0 22
=> changed inbound port from rdp to ssh

appservice-fileserver-standalone/azuredeploy.parameters.json
dnsNameForPublicIP doesn't allow capital letters.
=> Remove capitalization in dnsNameForPublicIP

bootstorm-vm-boot-time/azuredeploy.json
Fixed to point to Azure branch.
=> Fixed reference for Bootstorm

301-availability-set-elastic-storage-ecs/azuredeploy.json
added new 1804 vm types supporting from 16GB memory
=> Update azuredeploy.json for new vm types

201-vmss-windows-extension/azuredeploy.json
Update azuredeploy.json with latest api version
=> Update azuredeploy.json with latest api version

201-vmss-linux-extension/azuredeploy.parameters.json
Update parametter file to meet best practice
=> Update parametter file to meet best practice

appservice-fileserver-standalone/scripts/OnStartAzureVirtualMachineFileServer.ps1
1. Add missing $ for variable name
2. Remove extra space and new line from $cmd
=> Fix command line to invoke Single.ps1

hadoop-cluster/config/core-site.xml, hadoop-cluster/hadoop_cluster.json, hadoop-cluster/jumpbox_node.json, hadoop-cluster/master_node.json, hadoop-cluster/parameters.json, hadoop-cluster/scripts/hadoopSetup.sh, hadoop-cluster/worker_node.json
For performance reasons we want to support multiple data-disks.
=> Hadoop Support multiple data disks

rds-deployment-existing-ad/azuredeploy.json
Prevent double // in URI for assets.
=> remove trailing /

101-vm-linux-create-passwordfromkv/README.md, 101-vm-linux-create-passwordfromkv/azuredeploy.json, 101-vm-linux-create-passwordfromkv/azuredeploy.parameters.json, 101-vm-linux-create-passwordfromkv/metadata.json
There isn't one for linux vms, so I'm making one,
Currently still in development, will gladly accept criticisms.
Not ready for use
=> Create vm create linux with secret from keyvault

ethereum-consortium-blockchain/validation/automated-validation-variables.ps1
=> Remove sensitive information
